"""
Data models for SkillGap Resume & Fit Analyzer.
Defines Pydantic schemas for data validation across Student and HR workflows,
including official Roadmap.sh curriculum tracks grounded in the career guide PDF.
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class UserPersona(str, Enum):
    """User persona selecting the application view mode."""
    STUDENT = "Student / Candidate"
    HR = "HR / Recruiter"


class RoleCategory(str, Enum):
    """Categorization choices for engineering roles."""
    FRONTEND = "Frontend Engineering"
    BACKEND = "Backend Engineering"
    FULL_STACK = "Full Stack Engineering"
    DATA_AI = "Data Science / ML / AI"
    DEVOPS_CLOUD = "DevOps / Cloud Infrastructure"
    MOBILE = "Mobile App Development"
    GENERAL_ENGINEERING = "Software / Systems Engineering"
    NON_ENGINEERING = "Non-Engineering / Other"


class ScreeningResult(BaseModel):
    """
    Result from TypeSafe API System One primitives:
    - Noul gatekeeper (is_engineering_role)
    - Choice categorizer (detected_category)
    """
    is_engineering_role: bool = Field(
        ...,
        description="Noul gatekeeper decision: True if role is within engineering scope, False otherwise."
    )
    detected_category: RoleCategory = Field(
        ...,
        description="Choice categorizer decision indicating engineering subdiscipline."
    )
    scope_message: str = Field(
        ...,
        description="Scope guidance message explaining the screening decision."
    )
    confidence_score: float = Field(
        default=0.95,
        description="TypeSafe heuristic confidence score (0.0 to 1.0)."
    )


class CheckpointMilestone(BaseModel):
    """Structured milestone checkpoint directly from the PDF curriculum roadmaps."""
    checkpoint: str = Field(..., description="Name of the checkpoint from the roadmap.")
    topics: List[str] = Field(default_factory=list, description="Specific subtopics from the roadmap.")
    action: str = Field(..., description="Actionable next course of action starting with an action verb.")


class GapAnalysis(BaseModel):
    """
    Comprehensive analysis schema generated by Gemini AI and grounded in the PDF roadmaps.
    Adapts seamlessly for both Student and HR views.
    """
    is_match: bool = Field(
        ...,
        description="True if the candidate has strong/promising alignment with key core requirements."
    )
    match_status: str = Field(
        ...,
        description="Indicator: 'Strong Match', 'Partial Match', or 'Early-Stage Match'."
    )
    match_score_percentage: int = Field(
        default=75,
        ge=0,
        le=100,
        description="Estimated fit percentage based on core technical competencies."
    )
    summary: str = Field(
        ...,
        description="Direct, constructive assessment of the candidate profile vs target job description."
    )
    extracted_skills: List[str] = Field(
        default_factory=list,
        description="Skills identified directly in the resume that match the job description."
    )
    missing_skills: List[str] = Field(
        default_factory=list,
        description="Skills explicitly or implicitly sought by the role that are absent or unclear."
    )
    # Grounded in PDF curriculum roadmaps
    roadmap_track_name: str = Field(
        default="Engineering Career Track",
        description="Official roadmap track from the PDF (e.g. 'Frontend Developer Roadmap', 'Backend Developer Roadmap')."
    )
    roadmap_reference: str = Field(
        default="roadmap.sh Career Guide",
        description="Reference from the roadmap guide PDF."
    )
    path_forward: List[CheckpointMilestone] = Field(
        default_factory=list,
        description="Sequential checkpoints and path forward derived strictly from the roadmap PDF."
    )
    learning_roadmap: List[str] = Field(
        default_factory=list,
        description="[Student Focus] Actionable roadmap steps to bridge missing skills, starting with action verbs."
    )
    interview_questions: List[str] = Field(
        default_factory=list,
        description="[HR Focus] Targeted technical interview questions to probe skill gaps and depth."
    )
    hiring_recommendation: str = Field(
        default="Proceed to technical screening",
        description="[HR Focus] Concise recommendation for HR."
    )
